# when using the default proxy server port
local_backend: true 

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master) 

# These lines should *not* be indented
media_folder: "/assets/images/" # Media files will be stored in the repo under static/images/uploads
public_folder: "" # The src attribute for uploaded media will begin with /images/uploads

collections: 
  - 
    name: "candidates"
    label: "Кандидати"
    folder: "_candidates" 
    label_singular: "Candidate" 
    create: true 
    fields: 
      # Name 
      - 
        name: "name"
        label: "Име" 
        widget: "string" 

      # Age 
      - 
        name: "age"
        label: "Възраст" 
        widget: "number" 
        min: 1 
        max: 100 

      # Position
      -  
        name: "position"
        label: "Кандидат за" 
        widget: "string" 

       # Election Number 
      -  
        name: "election_number"
        label: "Номер" 
        widget: "number" 

       # Quote 
      -  
        name: "quote"
        label: "Цитат" 
        widget: "string" 

      # Facts 
      -  
        name: "facts" 
        label: "Накратко" 
        required: false 
        collapsed: true 
        widget: "object" 
        fields: 
          -  
            name: "born"
            label: "Роден(а)" 
            required: false 
            widget: "text" 

          -  
            name: "education"
            label: "Завършил(а)" 
            required: false 
            widget: "text" 
          -  
            name: "family"
            label: "Семейно положение" 
            required: false 
            widget: "text" 
          -  
            name: "work"
            label: "Работил(а)" 
            required: false 
            widget: "text" 

      # Photo 
      - 
        name: "photo"
        label: "Снимка" 
        widget: "image" 
        required: false 

      # Contacts 
      - 
        name: "contacts"  
        label: "Контакти" 
        widget: list 
         
        fields:
          - 
            name: "key"
            label: "Вид контакт" 
            widget: string 
            required: false
          - 
            name: "value"
            label: "Контакт" 
            widget: string 
            required: false

      # Body 
      - 
        name: "info"  
        label: "Информация" 
        widget: "list" 
        fields: 
          - 
            name: "heading"
            label: "Заглавие" 
            widget: "string" 
            required: false 
          - 
            name: "text" 
            label: "Текст"  
            widget: "list" 
            required: false   
            fields: 
              - 
                name: "paragraph" 
                label: "Параграф"  
                widget: "text" 
                required: false    

  -
    name: "news"
    label: "Събития" 
    folder: "_news" 
    label_singular: "Event" 
    identifier_field: heading 
    create: true 
    fields: 
      # Date 
      - 
        name: "date" 
        label: "Дата" 
        widget: "datetime" 
        date_format: "DD.MM.YYYY" 
        
      # Heading 
      - 
        name: "heading" 
        label: "Заглавие" 
        widget: "string" 
        required: false 

      # Text 
      - 
        name: "text"
        label: "Описание" 
        widget: "string" 
        required: false 

      # Image 
      - 
        name: "image"
        label: "Снимка" 
        widget: "image" 
        required: false 

      # Sections 
      - 
        name: "sections" 
        label: "Секции" 
        widget: "list" 
        fields: 
          # Heading 
          - 
            name: "heading" 
            label: "заглавие" 
            widget: "string" 
            required: false 
          # Text 
          - 
            name: "text" 
            label: "Текст" 
            widget: "list" 
            fields: 
              - 
                name: "paragraph" 
                label: "Параграф" 
                widget: "text" 

  -
    name: "reviews"
    label: "Мнения" 
    folder: "_reviews" 
    label_singular: "Review" 
    create: true 
    identifier_field: author.name 
    fields: 
      # Content 
      - 
        name: "sections" 
        label: "Секции" 
        widget: "list" 
        fields: 
          # Heading 
          - 
            name: "heading" 
            label: "Заглавие" 
            widget: "string" 
            required: false 
          # Text 
          - 
            name: "text" 
            label: "Текст" 
            widget: "list" 
            fields: 
              # Paragraph 
              - 
                name: "paragraph" 
                label: "Параграф" 
                widget: "text"
      
      # Author 
      - 
        name: "author" 
        label: "Автор" 
        widget: "object" 
        fields: 
          # Name 
          - 
            name: "name" 
            label: "Име" 
            widget: "string" 
          # Occupation 
          - 
            name: "occupation" 
            label: "Заетост" 
            widget: "string" 
            required: false 
          # Photo 
          - 
            name: "photo" 
            label: "Снимка" 
            widget: "image" 
            required: false 

  - 
    name: "pages"
    label: "Страници" 
    files: 
      - 
        name: "priorities" 
        label: "Priorities" 
        file: "_pages/priorities.md" 
        fields: 
          - 
            name: "heading"
            label: "Heading" 
            widget: "string" 
          - 
            name: "text"
            label: "Text" 
            widget: "list" 
            fields: 
              - 
                name: "paragraph"
                label: "Paragraph" 
                widget: "text" 
                required: false 
          - 
            name: "entry_list"
            label: "Entry List" 
            widget: "list" 
            fields: 
              - 
                name: "heading"
                label: "Heading" 
                widget: "string" 
                required: false 
              - 
                name: "paragraph"
                label: "Paragraph" 
                widget: "text" 
                required: false 
                  
              
